=== amedrod609/EjerciciosLMSGI/amigos.dtd
<!NOTATION JPG SYSTEM "image/jpeg">
<!NOTATION GIF SYSTEM "image/gif">
<!NOTATION PNG SYSTEM "image/png">

<!ELEMENT amigos (trabaja?, estudia*, drogadiccion)>
<!ATTLIST amigos estanAhi CDATA #FIXED 'siempre'>
<!ELEMENT trabaja (amigo* | amiga)>
<!ELEMENT amigo EMPTY>
<!ENTITY % caracteristicas "nombre ID #REQUIRED
                        colorPelo CDATA #IMPLIED
                        viveCon IDREF #IMPLIED
                        coche CDATA #IMPLIED">

<!ATTLIST amigo %caracteristicas; 
                imagenCoche NOTATION  (GIF | JPG | PNG) #IMPLIED>
<!ELEMENT estudia (amigo+ | amiga)>
<!ELEMENT drogadiccion (#PCDATA | droga)*>
<!ENTITY laDroga "Desde que se fueron a estudiar fuera están así, pero ya parece que levantan cabeza">
<!ELEMENT droga EMPTY>
<!ENTITY % caracDroga "nombre ID #REQUIRED
                        adicto IDREFS #REQUIRED
                        seQuierenQuitar (si | no) #IMPLIED">

<!ATTLIST droga %caracDroga;>

=== amedrod609/EjerciciosLMSGI/amigos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE amigos SYSTEM "amigos.dtd">

<amigos estanAhi="siempre">
    <trabaja>
        <amigo nombre="roldi" colorPelo="marron" coche="BMW" imagenCoche="JPG"/>
        <amigo nombre="dani" colorPelo="marron" viveCon="silver"/>
    </trabaja>
    <estudia>
        <amigo nombre="silver" colorPelo="rubio" viveCon="dani" coche="peugeot" imagenCoche="PNG"/>
        <amigo nombre="zanahorio" colorPelo="pelirrojo"/>
    </estudia>
    <drogadiccion> &ladroga;
        <droga nombre="cannabis" adicto="dani zanahorio" seQuierenQuitar="no"/>
        <droga nombre="diseÃ±o" adicto="dani roldi" seQuierenQuitar="si"/>
    </drogadiccion>
</amigos>
