=== amedrod609/EjerciciosLMSGI/practicaExamen.dtd
<!NOTATION JPG SYSTEM "image/jpeg">
  <!NOTATION GIF SYSTEM "image/gif">
  <!NOTATION PNG SYSTEM "image/png">

<!ELEMENT almacen (cocina, salon, dormitorio, facturas)>
<!ELEMENT cocina (campana+, encimera*, mesa*, alacena?)*>
<!ATTLIST cocina numhabitacion ID #REQUIRED>
<!ENTITY % caracteristicas "id  ID #REQUIRED
                            color CDATA #IMPLIED
                            madera CDATA #IMPLIED">
<!ELEMENT campana EMPTY>
<!ATTLIST campana %caracteristicas;>
<!ELEMENT encimera EMPTY>
<!ATTLIST encimera %caracteristicas;>
<!ELEMENT mesa EMPTY>
<!ATTLIST mesa %caracteristicas;>
<!ELEMENT salon (sofa, silla)>
<!ATTLIST salon numhabitacion ID #REQUIRED>
<!ELEMENT sofa EMPTY>
<!ATTLIST sofa %caracteristicas;
                 imagen NOTATION (GIF | JPG | PNG) #IMPLIED>
<!ELEMENT silla EMPTY>
<!ATTLIST silla %caracteristicas;>
<!ELEMENT dormitorio (cama | litera)>
<!ATTLIST dormitorio numhabitacion ID #REQUIRED>
<!ELEMENT cama (#PCDATA)>
<!ENTITY dondeVa 'a parte de esta factura'>
<!ATTLIST cama %caracteristicas;>
<!ELEMENT facturas (factura+)>
<!ELEMENT factura EMPTY>
<!ATTLIST factura articulos IDREFS #REQUIRED
                    habitacion IDREF #IMPLIED
                    telefono NMTOKEN #FIXED '667667667'
                    caja (a | b | c | d) #REQUIRED>

=== amedrod609/EjerciciosLMSGI/practicaExamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE almacen SYSTEM "practicaExamen.dtd">

<almacen>
    <cocina numhabitacion="C1">
        <campana id="a1" color="negro" madera="roble"/>
        <encimera id="b1" color="negro" madera="roble"/>
        <encimera id="a2" color="verde" madera="encina"/>
        <mesa id="b2" color="blanco" madera="pino"/>
        <mesa id="b3" color="negro" madera="melamina"/>
    </cocina>
    <salon numhabitacion="S1">
        <sofa id="c3" color="marron" madera="nogal" imagen="PNG"/>
        <silla id="d4" color="verde" madera="encina"/>
    </salon>
    <dormitorio numhabitacion="D1">
        <cama id="e5" color="marron" madera="contrachapado">
            El colchon va &dondeVa;
        </cama>

    </dormitorio>
    <facturas>
        <factura articulos="a1 a2 b3" habitacion="D1" telefono="667667667" caja="b" />
        <factura articulos="a1 c3 e5" telefono="667667667" caja="a" />
    </facturas>
</almacen>
